require_relative "abilities.rb"
require_relative "background.rb"
require_relative "class.rb"
require_relative "gender.rb"
require_relative "race.rb"
require_relative "sort.rb"
require_relative "contains.rb"